export const projects = [
  {
    id: 'sudip-parajuli',
    title: 'Sudip Parajuli',
    subtitle: 'Personal Portfolio',
    category: 'Web Design',
    tags: ['Next.js', 'GSAP', 'Framer Motion'],
    image: '/images/projects/sudip-parajuli.jpg',
    color: '#1A1A2E',
    url: 'https://sudip-parajuli.github.io/PersonalPortfolio/',
    year: '2024',
  },
  https://sudip-parajuli.com.np
    {
    id: 'sudip-parajuli',
    title: 'Sudip Parajuli',
    subtitle: 'Personal Portfolio',
    category: 'Web Design',
    tags: ['Next.js', 'GSAP', 'Framer Motion'],
    image: '/images/projects/sudip-parajuli3D.jpg',
    color: '#1A1A2E',
    url: ' https://sudip-parajuli.com.np',
    year: '2026',
  },
  {
    id: 'easymoto',
    title: 'EasyMoto',
    subtitle: 'Automotive E-Commerce',
    category: 'E-Commerce',
    tags: ['React', 'WooCommerce', 'SEO'],
    image: '/images/projects/easymoto.jpg',
    color: '#0F2B4A',
    url: 'https://www.easymoto.com.np/public-home/',
    year: '2024',
  },
  {
    id: 'techwired',
    title: 'TechWired Solutions',
    subtitle: 'Corporate Technology',
    category: 'Web Design',
    tags: ['Next.js', 'Corporate', 'CMS'],
    image: '/images/projects/techwired.jpg',
    color: '#0D1B2A',
    url: 'https://techwired-solutions.vercel.app',
    year: '2024',
  },
  {
    id: 'aryal-farm',
    title: 'Aryal Farm',
    subtitle: 'Agriculture & Branding',
    category: 'Branding',
    tags: ['WordPress', 'Branding', 'SEO'],
    image: '/images/projects/aryal-farm.jpg',
    color: '#0F2A10',
    url: 'https://aryalfarm.com.np',
    year: '2025',
  },
  {
    id: 'amicus',
    title: 'Amicus',
    subtitle: 'Legal Professional Services',
    category: 'Web Design',
    tags: ['WordPress', 'Professional', 'Legal'],
    image: '/images/projects/amicus.jpg',
    color: '#1A1208',
    url: 'https://amicus.com.np',
    year: '2025',
  },
];
