export const projects = [
  {
    id: 'sudip-parajuli',
    title: 'Sudip Parajuli',
    subtitle: 'Personal Portfolio',
    category: 'Web Design',
    tags: ['Next.js', 'GSAP', 'Framer Motion'],
    image: '/images/projects/sudip-parajuli.jpg',
    color: '#1A1A2E',
    url: 'https://sudip-parajuli.github.io/PersonalPortfolio/',
    year: '2024',
  },
  {
    id: 'sudip-parajuli-3d',
    title: 'Sudip Parajuli',
    subtitle: '3D Personal Portfolio',
    category: 'Web Design',
    tags: ['Next.js', 'GSAP', 'Framer Motion', 'Three.js'],
    image: '/images/projects/sudip-parajuli3D.png',
    color: '#0A0A16',
    url: 'https://sudip-parajuli.com.np',
    year: '2026',
  },
  {
    id: 'paila-retro',
    title: 'Paila Retro',
    subtitle: 'Modern Retro Restaurant',
    category: 'Web Design',
    tags: ['Next.js', 'TailwindCSS', 'Aesthetics'],
    image: '/images/projects/paila-retro.png',
    color: '#1F110A',
    url: 'https://pailarestrosample-web.vercel.app/',
    year: '2026',
  },
  {
    id: 'easymoto',
    title: 'EasyMoto',
    subtitle: 'Automotive E-Commerce',
    category: 'E-Commerce',
    tags: ['React', 'WooCommerce', 'SEO'],
    image: '/images/projects/easymoto.jpg',
    color: '#0F2B4A',
    url: 'https://www.easymoto.com.np/public-home/',
    year: '2024',
  },
  {
    id: 'techwired',
    title: 'TechWired Solutions',
    subtitle: 'Corporate Technology',
    category: 'Web Design',
    tags: ['Next.js', 'Corporate', 'CMS'],
    image: '/images/projects/techwired.jpg',
    color: '#0D1B2A',
    url: 'https://techwired-solutions.vercel.app',
    year: '2024',
  },
  {
    id: 'aryal-farm',
    title: 'Aryal Farm',
    subtitle: 'Agriculture & Branding',
    category: 'Branding',
    tags: ['WordPress', 'Branding', 'SEO'],
    image: '/images/projects/aryal-farm.jpg',
    color: '#0F2A10',
    url: 'https://aryalfarm.com.np',
    year: '2025',
  },
  {
    id: 'amicus',
    title: 'Amicus',
    subtitle: 'Legal Professional Services',
    category: 'Web Design',
    tags: ['WordPress', 'Professional', 'Legal'],
    image: '/images/projects/amicus.jpg',
    color: '#1A1208',
    url: 'https://amicus.com.np',
    year: '2025',
  },
  {
    id: 'kb-resort',
    title: 'Kwality Beach Resort',
    subtitle: 'Tranquil Riverside Resort',
    category: 'Web Design',
    tags: ['HTML', 'CSS', 'GSAP', 'Responsive'],
    image: '/images/projects/kb-resort.jpg',
    color: '#0A2E2F',
    url: 'https://rbresortredesign.vercel.app/',
    year: '2026',
  },
  {
    id: 'five-star-hotel',
    title: 'Five Star Hotel',
    subtitle: 'Premium Hospitality Platform',
    category: 'Web Design',
    tags: ['Next.js', 'TailwindCSS', 'Booking System'],
    image: '/images/projects/five-star-hotel.jpg',
    color: '#2B1E10',
    url: 'https://5starhotelsample.vercel.app/',
    year: '2026',
  },
];

